### ISSUE TITLE
WEB - Company Revenue

### ISSUE THREAD

**Issue by aa-software2112** [lkadian/WikipediaData#39]
As a user, I would like to view the revenue of a given company for its history of operation and on the same page where all other company-related data is viewable.

- [x] Create a revenue page mockup [#40]
- [x] Create a revenue database. [#41]
- [x] Implement revenue endpoint [#41]
- [x] Create a suiting front-end implementation based on mockup for this revenue page. [#42]

Story Points: 8
Ideal Hours: 9.5
Risk: LOW
Priority: HIGH

**Comment by aa-software2112** [comment]
The database is created - it is up on the drive in the usual folder .

**Comment by aa-software2112** [comment]
The endpoint is created, and now we support local packages. They can all be found in this PR #54

**Comment by anthonyle17** [comment]
Done via these PRs:
[Endpoints](https://github.com/lkadian/WikipediaData/pull/54) and [Frontend](https://github.com/lkadian/WikipediaData/pull/59).
