### ISSUE TITLE
WEB - Company Miscellaneous Properties 

### ISSUE THREAD

**Issue by anthonyle17** [lkadian/WikipediaData#55]
As a user, I would like to view miscellaneous properties of a given company:
- [x] industry
- [x] subsidiaries
- [x] ceos
- [x] products or materials produced

Sub-tasks/issues:
- [x] Create a page mockup
- [x] Obtain misc. fields from Wikidata [#52]
- [x] Create tables in database [#57]
- [x] Implement endpoints [#57]
- [x] Create a suiting front-end implementation based on mockup for this revenue page. [#56]

Story Points: 8
Ideal Hours: 12
Risk: LOW
Priority: HIGH

**Comment by anthonyle17** [comment]
[Mockup](https://github.com/lkadian/WikipediaData/wiki/Mockups#company-page-11-with-revenue-chart) is the one previously created already.
